# This is a basic workflow to help you get started with Actions

name: Build and Push to ECR, Update IaC Repo for Argo CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # 깃헙액션의 워크플로를 트리거하는 조건
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # 리포지토리 클론
      - name: Checkout code
        uses: actions/checkout@v4

      # AWS 환경 변수 설정
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      # AWS ECR 로그인
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: private

      # 도커 이미지 빌드
      - name: Build Docker image
        run: |
          TAG=${{ github.sha }}
          export DOCKER_BUILDKIT=1
          docker build --platform linux/amd64 \
            --build-arg GIT_TOKEN="${{ secrets.GIT_TOKEN }}" \
            -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-2.amazonaws.com/my-app:$TAG .
      

      # ECR에 도커 이미지 푸시
      - name: Push to Amazon ECR
        run: |
          TAG=${{ github.sha }}
          docker push ${{ secrets.ECR_URI }}

      # GitHub 사용자 설정
      - name : Set Git config
        run: |
          git config --global user.name ${{ secrets.GIT_USER_NAME }}
          git config --global user.email ${{ secrets.GIT_USER_EMAIL }}
